### ISSUE TITLE
在连接状态，拔了usb 串口，日志一直警告的报错，能监听usb串口连接状态吗

### ISSUE THREAD

**Issue by wanglianghai** [xmaihh/Android-Serialport#37]
拔了usb 串口的警告日志 2.1.1 版本
java.io.IOException: I/O error
at java.io.FileInputStream.available0(Native Method)
at java.io.FileInputStream.available(FileInputStream.java:323)
at tp.xmaihh.serialport.stick.BaseStickPackageHelper.execute(BaseStickPackageHelper.java:18)
at tp.xmaihh.serialport.SerialHelper$ReadThread.run(SerialHelper.java:95)

**Comment by xmaihh** [comment]
可以通过监听串口文件描述符的可读可写状态来判断串口连接状态。当串口拔出时，文件描述符变为不可读写，此时可以捕获到相应的异常，并处理连接断开的逻辑。具体实现可以在SerialPort类中添加一个方法来判断文件描述符是否可读可写，然后在读写串口的方法中进行调用，捕获异常并进行相应的处理。
