### ISSUE TITLE
java.lang.NullPointerException: println needs a message   at android.util.Log.println_native(Native Method)                                                                                                            	at android.util.Log.e(Log.java:236)                                                                                                            	at tp.xmaihh.serialport.SerialHelper$ReadThread.run(SerialHelper.java:114)

### ISSUE THREAD

**Issue by blankhang** [xmaihh/Android-Serialport#45]
![image](https://github.com/xmaihh/Android-Serialport/assets/3981276/f021f4c0-c158-4647-b071-799e37328eb7)

![image](https://github.com/xmaihh/Android-Serialport/assets/3981276/66360589-c209-48cf-a88f-2423d5fb913a)

偶尔会遇到这个NPE问题。。。不知道怎么解决
```kotlin
    protected lateinit var mTTYS1SerialPort: SerialPortHelper

    protected lateinit var mTTYS4SerialPort: SerialPortHelper

    companion object {
        private const val TAG = "ATOneDevice"
        private const val BIT_RATE = 115200
        private const val STOP_BIT = 1
        private const val DATA_BIT = 8
        private const val PARITY = 0    // 不使用校验
        private const val FLOW_CON = 0  // 不使用流控制
        private const val FLAGS = 0     // 正常模式
    }

    @Throws(SecurityException::class, IOException::class, InvalidParameterException::class)
    private fun tryOpenSerialPort(): Boolean {
        Log.i(TAG, "打开LORA串口 START")

        // 第一次连接需要同时打开S1和S4串口
        mTTYS1SerialPort = SerialPortHelper(loraS1SerialPort, BIT_RATE)
        mTTYS4SerialPort = SerialPortHelper(loraS4SerialPort, BIT_RATE)

        mTTYS1SerialPort.stickPackageHelper = SpecifiedStickPackageHelper("AT".toByteArray(), "\r\n".toByteArray())
        mTTYS1SerialPort.dataBits = DATA_BIT
        mTTYS1SerialPort.stopBits = STOP_BIT
        mTTYS1SerialPort.parity = PARITY
        mTTYS1SerialPort.flowCon = FLOW_CON
        mTTYS1SerialPort.setDataReceiveCallback(object : IDataReceive {
            override fun onReceived(cmdStr: String, serialPort: String) {
                mCurrentSerialPortIsS1 = true
                onReceived(cmdStr)
            }
        })
        mTTYS1SerialPort.open()
        mTTYS1IsConnected = true
        Log.i(TAG, "打开LORA S1串口")

        mTTYS4SerialPort.stickPackageHelper = SpecifiedStickPackageHelper("AT".toByteArray(), "\r\n".toByteArray())
        mTTYS4SerialPort.dataBits = DATA_BIT
        mTTYS4SerialPort.stopBits = STOP_BIT
        mTTYS4SerialPort.parity = PARITY
        mTTYS4SerialPort.flowCon = FLOW_CON
        mTTYS4SerialPort.setDataReceiveCallback(object : IDataReceive {
            override fun onReceived(cmdStr: String, serialPort: String) {
                mCurrentSerialPortIsS1 = false
                onReceived(cmdStr)
            }
        })
        mTTYS4SerialPort.open()
        mTTYS4IsConnected = true
        Log.i(TAG, "打开LORA S4串口")

        Log.i(TAG, "打开LORA串口 END")
        return true
    }
```

**Comment by blankhang** [comment]
感谢回复，我想确认下 这是你内部的方法打印出来的NPE 我好像没有很好的解决办法吧？

**Comment by xmaihh** [comment]
你切换到源码[tag v2.1.1](https://github.com/xmaihh/Android-Serialport/tree/v2.1.1/)，用依赖project的方式，然后修改代码试试能否解决这个问题

```
    implementation project(path: ':serialport')
//    implementation 'io.github.xmaihh:serialport:2.1.1'
```

**Comment by blankhang** [comment]
![image](https://github.com/xmaihh/Android-Serialport/assets/3981276/ee0068ff-08f4-41ad-996f-eafc41967b98)
我整个拉下来 放到我的项目中 跑不起来  整个打包又只看到apk 不知道怎样把这个打成jar

你能不能帮我建一个新的测试版本 让我跑下看看还会不会NPE？

**Comment by xmaihh** [comment]
你要下载tag v2.1.1的源码，https://github.com/xmaihh/Android-Serialport/releases/tag/v2.1.1

**Comment by blankhang** [comment]
是下的2.1.1 build出来是apk 直接copy这个串口文件夹build报错

**Comment by xmaihh** [comment]
当你遇到 "Gradle object instantiation exception"，通常意味着在 Gradle 构建过程中实例化对象时出现问题。发生这种情况的原因有多种，例如配置不正确或缺少依赖项。

要解决此问题，您可以尝试以下步骤：

1. 检查您的 Gradle 配置：验证您的 build.gradle 文件中是否正确配置了所有必需的依赖项和插件。确保依赖项的版本与您的项目兼容。
2.  执行`./gradlew clean build`，有时，可以通过清理和重建项目来解决问题。
3. 更新 Gradle 版本：如果您使用的是过时版本的 Gradle，请考虑将其更新到最新的稳定版本。您可以通过修改项目的 gradle/wrapper/gradle-wrapper.properties 文件中的 Gradle 包装器设置来完成此操作。
4. 检查冲突的依赖项：您的项目中可能存在冲突的依赖项。检查 build.gradle 文件中的依赖项并确保不存在重复或不兼容的版本。您可以使用 ./gradlew dependencies 命令检查依赖项冲突。

**Comment by blankhang** [comment]
拉2.1.1的源码改114行判断空后 运行半天没有再出现NPE错误,建议更新一下这里

https://github.com/xmaihh/Android-Serialport/pull/46
