### ISSUE TITLE
serialHelper.close()

### ISSUE THREAD

**Issue by cnhuz** [xmaihh/Android-Serialport#49]
请问为啥执行`serialHelper.close()`之后，Logcat一直打印这个错误
```
java.io.IOException: Bad file descriptor
	at java.io.FileInputStream.available0(Native Method)
	at java.io.FileInputStream.available(FileInputStream.java:323)
	at tp.xmaihh.serialport.stick.BaseStickPackageHelper.execute(BaseStickPackageHelper.java:18)
	at tp.xmaihh.serialport.SerialHelper$ReadThread.run(SerialHelper.java:95)
```

**Comment by xmaihh** [comment]
请看看源码https://github.com/xmaihh/Android-Serialport/blob/master/serialport/src/main/java/tp/xmaihh/serialport/stick/BaseStickPackageHelper.java#L31，

是否抛出异常，关于该做什么，你有 3 个选择：

1. 捕获并吞掉异常，将其丢弃
2. 捕获并吞掉异常，让它向上传播
3. 捕获异常，并抛出不同类型的异常

请根据您的需要酌情处理。
